app = "web-agent-rs"
primary_region = "iad"

[deploy]
    strategy = "rolling"

[build]
    dockerfile = "Remote.Dockerfile"
    deploy-target = "app"



[env]
    OPENAI_API_KEY=""
    OPENAI_API_BASE=""
    GENAISCRIPT_MODEL_LARGE=""
    GENAISCRIPT_MODEL_SMALL=""
    GENAISCRIPT_MODEL_PROVIDER=""

    SEARXNG_API_BASE_URL=""
    SEARXNG_PASSWORD=""
    BING_SEARCH_API_KEY = ""
    TAVILY_API_KEY = ""
    PERIGON_API_KEY= ""
    CEREBRAS_API_KEY = ""
    CCC_API_KEY=""
    HF_API_KEY=""

[http_service]
    internal_port = 3006
    force_https = true
    auto_stop_machines = "suspend"
    auto_start_machines = true
    # automatic shutdown when not in use
    min_machines_running = 0

    [http_service.http_options]
        idle_timeout = 180


    [[http_service.checks]]
        interval = '30s'
        timeout = '5s'
        grace_period = '10s'
        method = 'GET'
        path = '/health'

[[vm]]
    size = "performance-1x"


[[mounts]]
source = "web_agent_app_mount"
destination = "/app/data"
